### ISSUE TITLE
这个东西是真的不错，一直在找这个有向图转换的功能

### ISSUE THREAD

**Issue by hawind** [givingwu/flow-design-center#1]
这个东西是真的不错，一直在找这个有向图转换的功能
折腾了好久，感谢作者，另外想问问作者，这个可以投入生产使用吗，有没有已知的bug啥的

**Comment by givingwu** [comment]
你可以大胆的投入生产环境使用，我司已使用此项目两年有余，而且接入到了其他 BU。（期间绘图及数据方面从没有跟我提过 bug, 欢迎来自社区的你提 issue）
